### ISSUE TITLE
https://github.com/tylerszabo/RGB-Fusion-Tool/issues/39

### ISSUE THREAD

**Issue by deathortranshumanism** [Cheerpipe/RGBFusionCli#6]
Hola Senor:

I have come across your tool in the https://github.com/tylerszabo/RGB-Fusion-Tool/issues/39 where someone asked for support for X570 motherboards. I have an Aorus Master.

But I do not understand how to either use your RGBFusion390SetColor.exe or the original. I do not know how to "build" something. All I have done is to copy your RGBFusion390SetColor.exe into the RGBFusion folder in windows.

I run from cmd.exe that your --areas command is working, so it is accepting arguments.

but everything else does not work? Please help. Thanks

**Comment by Cheerpipe** [comment]
Hola deathortranshumanism.

Fastest way is to follow the nexts steps:

1.- Download rgbfusion390setcolor (https://github.com/Cheerpipe/RGBFusion390SetColor/releases/download/0.0.4/RGBFusion390SetColor_v0.0.4.zip)

2.- Uncompres RGBFusion390SetColor.exe and copy to **C:\Program Files (x86)\GIGABYTE\RGBFusion**

3.- Uncompress RGBFusion390Sender.dll and copy to **C:\Program Files\Aurora**

4.- Download https://github.com/Cheerpipe/RGBFusion390SetColor/tree/master/Aurora/Scripts/Devices

5.- In the file RgbFusionMB_VGA_native.cs change the line:


`		string command = string.Format(" --sa:1:{3}:{0}:{1}:{2}  --sa:2:{3}:{0}:{1}:{2}  --sa:3:{3}:{0}:{1}:{2} --sa:5:{5}:{0}:{1}:{2} --sa:6:{5}:{0}:{1}:{2}  --sa:8:{6}:{0}:{1}:{2} --sa:9:{7}:{0}:{1}:{2}", Convert.ToInt32(color.R*color.A/255).ToString(), Convert.ToInt32(color.G*color.A/255).ToString(), Convert.ToInt32(color.B*color.A/255).ToString(), 0 , 0, 0, 0 , 0) ;`

To

`		string command = string.Format(" --sa:1:-1:{0}:{1}:{2}", Convert.ToInt32(color.R*color.A/255).ToString(), Convert.ToInt32(color.G*color.A/255).ToString(), Convert.ToInt32(color.B*color.A/255).ToString(), 0 , 0, 0, 0 , 0) ;`

6.- Copy the modified file to **C:\Program Files\Aurora\Scripts\Devices**

7.- Restart Aurora and check Configuration->Devices and Wrappers.  You sould see something like RGB Fusion Z390 wrapper in device list. Click enable and Start.

8.- Execute RGBFusion390SetColor.exe without any parameter. 

9.- (Optional) Create a RGBFusion390SetColor.exe shortcut in the startup foler. Just open Run dialog (Win+R) and execute the command "Shell:Startup" (without quotes) and paste your shortcut.

**Comment by deathortranshumanism** [comment]
> Hola deathortranshumanism.
> 
> Fastest way is to follow the nexts steps:
> 
> 1.- Download rgbfusion390setcolor (https://github.com/Cheerpipe/RGBFusion390SetColor/releases/download/0.0.4/RGBFusion390SetColor_v0.0.4.zip)
> 
> 2.- Uncompres RGBFusion390SetColor.exe and copy to **C:\Program Files (x86)\GIGABYTE\RGBFusion**
> 
> 3.- Uncompress RGBFusion390Sender.dll and copy to **C:\Program Files\Aurora**
> 
> 4.- Download https://github.com/Cheerpipe/RGBFusion390SetColor/tree/master/Aurora/Scripts/Devices
> 
> 5.- In the file RgbFusionMB_VGA_native.cs change the line:
> 
> ` string command = string.Format(" --sa:1:{3}:{0}:{1}:{2} --sa:2:{3}:{0}:{1}:{2} --sa:3:{3}:{0}:{1}:{2} --sa:5:{5}:{0}:{1}:{2} --sa:6:{5}:{0}:{1}:{2} --sa:8:{6}:{0}:{1}:{2} --sa:9:{7}:{0}:{1}:{2}", Convert.ToInt32(color.R*color.A/255).ToString(), Convert.ToInt32(color.G*color.A/255).ToString(), Convert.ToInt32(color.B*color.A/255).ToString(), 0 , 0, 0, 0 , 0) ;`
> 
> To
> 
> ` string command = string.Format(" --sa:1:-1:{0}:{1}:{2}", Convert.ToInt32(color.R*color.A/255).ToString(), Convert.ToInt32(color.G*color.A/255).ToString(), Convert.ToInt32(color.B*color.A/255).ToString(), 0 , 0, 0, 0 , 0) ;`
> 
> 6.- Copy the modified file to **C:\Program Files\Aurora\Scripts\Devices**
> 
> 7.- Restart Aurora and check Configuration->Devices and Wrappers. You sould see something like RGB Fusion Z390 wrapper in device list. Click enable and Start.
> 
> 8.- Execute RGBFusion390SetColor.exe without any parameter.
> 
> 9.- (Optional) Create a RGBFusion390SetColor.exe shortcut in the startup foler. Just open Run dialog (Win+R) and execute the command "Shell:Startup" (without quotes) and paste your shortcut.
> 
> PD: Your paths may be different than mine

What is Aurora & Does this step work for X570 AMD boards? I tried your programme because someone said it worked for them. But I do not have a Z390 Intel board.
