### ISSUE TITLE
[FR] Aurora integration

### ISSUE THREAD

**Issue by Hukuma1** [Cheerpipe/RGBFusionCli#7]
**Is your feature request related to a problem? Please describe.**
Can we get your plugin to be distributed with Project Aurora natively? There's a very old issue (which is how I found this amazing utility in the first place) on their page, but no PR submitted to actually integrate your utility with default installation of Aurora.

**Describe the solution you'd like**
Adding the files by default to Aurora installation.

**Describe alternatives you've considered**
Installing manually and editing the Script file to include my x470 board manually is possible, but not as seamless obviously. :)

**Additional context**
For some reason using the latest nightly release of Aurora I cannot get RGBFusion390SetColor to work. Did something change on their end? (for x470 motherboard, not 390) (it shows connected in devices, but colors do not change)

**Comment by Hukuma1** [comment]
And off topic: But is it possible to use your utility without installing bloaty RGBFusion software? Am I able to just rip certain .dlls from the installation folder? Would love to uninstall and just use your solution.

**Comment by Cheerpipe** [comment]
Aurora is a very mature and stable software whereas my tool is still very inestable. That is why i did not create an aurora device integration....get. By the time the easyest way to integrate my tool is to use the default scripted device (i am working in a new scripted device with the ability of start and stop rgbfusioncli).

**Comment by Hukuma1** [comment]
Gotcha. Keep up the great work!

If you want any testers let me know. I have Gigabyte x470 avail to test.

**Comment by Cheerpipe** [comment]
Pls try new release 0.0.5 and report back.

> For some reason using the latest nightly release of Aurora I cannot get RGBFusion390SetColor to work. Did something change on their end? (for x470 motherboard, not 390) (it shows connected in devices, but colors do not change)

Can you elaborate?  (wont work from command line, from aurora? did you install a new version of RGBFusion? Is RGBFusion closed?) Thanks in advance.

**Comment by Hukuma1** [comment]
Sorry I meant with Aurora.

Okay with new RGBFusionCLI, I place the exe still in RGB Fusion Dir? Or I can place the RGBFusionCLI and the 2 dll files all into Aurora main dir? Is there a different/updated device script?

**Comment by Hukuma1** [comment]
Okay, re-read the install instructions! :)

Works just find as CLI from cmd. .e.g 

`C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:-1:0:255:0:0:9:9` = Red in all zones on my x470. Will now try to link to Aurora.

**Comment by Hukuma1** [comment]
Still using CLI to test the new transaction commands. They don't seem to be doing anything.

Or must I execute in a batch file?

```
C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --transactionstart

C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:-1:0:255:255:255

C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:-1:0:255:0:255

C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:-1:0:255:0:0

C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --transactioncommit
```

If I do those commands separately `RGBFUsionCLI --setarea:-1:0:255:0:0` the color changes as expected.

**Comment by Cheerpipe** [comment]
> Still using CLI to test the new transaction commands. They don't seem to be doing anything.
> 
> Or must I execute in a batch file?
> 
> ```
> C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --transactionstart
> 
> C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:0:0:255:255:255
> 
> C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:1:0:255:0:255
> 
> C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --setarea:2:0:255:0:0
> 
> C:\Program Files (x86)\GIGABYTE\RGBFusion>RGBFUsionCLI --transactioncommit
> ```
> 
> If I do those commands separately `RGBFUsionCLI --setarea:-1:0:255:0:0` the color changes as expected.

You are using -1 area wildcard. Transactions works only with a specific areaID. (0 or greater).

I just upladed v0.0.6 r

**Comment by Hukuma1** [comment]
Ah makes sense. Will toy around with zones soon then to test.

Aurora is giving this on v.6:

```
[ERROR] 13:42:57: Device script for RGB Fusion encountered an error during UpdateDevice. Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'RGBFusion.UpdateDevice(System.Collections.Generic.Dictionary<Aurora.Devices.DeviceKeys,System.Drawing.Color>, bool)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , Object , Dictionary`2 , Boolean )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Aurora.Devices.ScriptedDevice.ScriptedDevice.UpdateDevice(Dictionary`2 keyColors, DoWorkEventArgs e, Boolean forced) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 148
[INFO] 13:42:59: Device, RGB Fusion, was not initialized
```

**Comment by Cheerpipe** [comment]
Are you using the new scripedDevice?

**Comment by Hukuma1** [comment]
I am, from here: https://github.com/Cheerpipe/RGBFusionCli/blob/master/Aurora/Scripts/Devices/RgbFusion.cs

Using latest nightly Aurora from here: https://ci.appveyor.com/project/antonpup/aurora/builds/32917363/artifacts (has support for multiple device layout)

**Comment by Cheerpipe** [comment]
Dont use that build of aurora. It has some breaking changes and heavy work in progress.

Use this instead:

https://ci.appveyor.com/project/antonpup/aurora/builds/32905253

**Comment by Hukuma1** [comment]
Gotcha. This one works without a hitch!

**Comment by Hukuma1** [comment]
Only 'zone' that doesn't change it seems is the ring around the Wraith Prism cooler. But I think this is because it requires another dll just for that silly ring. https://landing.coolermaster.com/pages/amd-ryzen-wraith-prism-rgb-software/

**Comment by Cheerpipe** [comment]
> Only 'zone' that doesn't change it seems is the ring around the Wraith Prism cooler. But I think this is because it requires another dll just for that silly ring. https://landing.coolermaster.com/pages/amd-ryzen-wraith-prism-rgb-software/

It seems like the fan is not rgbfusion compatible.

Is the fan connected to a main board rgb/argb pin header or USB?

**Comment by Hukuma1** [comment]
It’s actually connected to both. So the actual fan light is run fusion compatible, but the ring info is sent via the usb cable. Still boggles my mind. So the only way to change ring is to install that utility even though the fan itself can be changed with rgb fusion.

**Comment by Hukuma1** [comment]
https://press.razer.com/product-news/light-up-your-amd-wraith-prism-cooler-with-razer-chroma/

So basically the fan LED is what can be controlled by RGB Fusion (and RGBFusionCLI). The ring LED and logo LED cannot. Unless I guess someone can reverse the dll calls the CoolerMaster utility makes. Looks like Project Aurora already has a ticket from last year in place: https://github.com/antonpup/Aurora/issues/1768

**Comment by Cheerpipe** [comment]
Did you check this?

https://gitlab.com/CalcProgrammer1/OpenRGB

Is the best rgb controller software out there. It has some problems with smbus devices in windows but should work well with USB devices like your fan.

**Comment by Hukuma1** [comment]
Very cool, didn't know that existed! I guess I only searched Github before. ;)

**Comment by Hukuma1** [comment]
Making this issue as closed since your latest version along with script works for Aurora. Thanks a lot!

**Comment by Cheerpipe** [comment]
Thanks, corrected.
